-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgKin1EMhALC59dUE9
EIYNWXiJgBjzLZX/kfHJraZFSeegCgYIKoZIzj0DAQehRANCAAT2oVnvYcfkSdEA
6FnirPLOTL8jJdgFGHzymLJja6guPaax2OcylPTHivKFBwcHOpIaarHl0kZzHJlM
3SkMy3ZF
-----END PRIVATE KEY-----